---
linters-settings:
  funlen:
    ignore-comments: true
  revive:
    rules:
      - name: exported
        disabled: true
  stylecheck:
    checks: ["all", "-ST1000"]
linters:
  enable-all: true
  disable:
    ### deprecated, archived or obsolette by authors
    - paralleltest
    - tenv # replaced by usetesting
    ### disabled by me
    - depguard
    - exhaustruct
    - wrapcheck
issues:
  exclude-use-default: false
